name: Pull from External Repo

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  pull-external-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WEBSITE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Target Repo
        run: |
          git clone git@github.com:yangsx95/notes-life.git
          ls -la notes-life/  # 验证文件是否存在

      - name: Process Files
        run: |
          cp -r notes-life ./local-docs/  # 示例：复制到本地目录
