name: Deploy notes to GithubPage using Docusaurus

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  pull-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TARGET_REPO_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone notes-life Repo
        run: |
          git clone git@github.com:yangsx95/notes-life.git
          ls -la notes-life/  # 验证文件是否存在

      - name: Clone notes Repo
        run: |
          git clone git@github.com:yangsx95/notes.git
          ls -la notes/  # 验证文件是否存在      

  generate-static:
    - name: Install and Build
      run: |
        npm install
        npm run-script build


